### ISSUE TITLE
authentication URL not working

### ISSUE THREAD

**Issue by DharaVaghasiya** [ibanity/ibanity-dotnet#1]
Hi, I'm trying to connect through authentication URL for this web app but it's not working for me so can you please guide me from where can I generate authentication URL for my app. thank you

**Comment by damienbr** [comment]
Hello,

Did you already check this part of the documentation? https://documentation.ibanity.com/ponto-connect/1/products#access-authorization
There are samples for sandbox and live authentication URL.

**Comment by stephdewit** [comment]
Hello.

I think we took care of this issue on the Slack channel.

I'm going to close it here, feel free to reopen if it occurs again.
