### ISSUE TITLE
Small documentation error

### ISSUE THREAD

**Issue by des2k7** [ibanity/ibanity-dotnet#28]
The "create supplier" tip in my VS gave me a small heart attack :-)

![image](https://github.com/user-attachments/assets/c5f1695f-3e8a-4a22-8595-47435aa565d4)

**Comment by stephdewit** [comment]
Hello @des2k7

I just published a new [0.6.2 release](https://www.nuget.org/packages/Ibanity/0.6.2) with the documentation fixed.
