### ISSUE TITLE
e-Invoicing: Get single Peppol inbound document

### ISSUE THREAD

**Issue by joachimvanbelle** [ibanity/ibanity-dotnet#30]
Hi, is it possible to get a single Peppol inbound document? I can't seem to find it.
Or is this a request we need to implement ourselves?

**Comment by stephdewit** [comment]
Hello @joachimvanbelle 

A new version [0.6.3](https://www.nuget.org/packages/Ibanity/0.6.3) of the NuGet package has been released.

It contains new methods to get a Peppol inbound document as an object as well as an XML document.
