### ISSUE TITLE
[Codabox Connect] Relationship for documents when searching for multiple clients

### ISSUE THREAD

**Issue by thomasvdb** [ibanity/ibanity-dotnet#5]
When searching documents for multiple clients in one call, it seems that the [DocumentSearchResponse](https://github.com/ibanity/ibanity-dotnet/blob/ac68d1fa9258228948e8fdcc040258f401127a53/src/Client/Products/CodaboxConnect/Models/DocumentSearch.cs#L36) class doesn't indicate the relationship with the requested clients.

In the REST API, however, the relationship is available in the response via the `included.documents` property.

![Screenshot 2023-02-02 at 16 11 31](https://user-images.githubusercontent.com/1577109/216364622-d7c6b569-be08-4676-aaf1-c8d8211b5ba6.png)

Is this something that will be added in the near future?
Looping through the returned documents and fetching additional details is not possible at the moment because we don't know to which client the document belongs to (unless we only fetch for 1 client at the time).

```
var documentSearchRequest = new DocumentSearch
{
    DocumentType = "bankAccountStatement", 
    From = new DateTimeOffset(2022, 1, 1, 0, 0, 0, TimeSpan.Zero),
    To = new DateTimeOffset(2023, 1, 1, 0, 0, 0, TimeSpan.Zero)
};
        
var documentSearchResponse = await ibanityService.CodaboxConnect.DocumentSearches.Create(
    token, 
    consent.AccountingOfficeId, 
    documentSearchRequest,
    new [] { "customerCompanyNumber1", "customerCompanyNumber2" },
    100
);

foreach (var document in documentSearchResponse.Documents)
{
        var statement = await ibanityService.CodaboxConnect.BankAccountStatements.Get(token, consent.AccountingOfficeId, "company number required here", Guid.Parse(document.Id));
}
```

**Comment by stephdewit** [comment]
Hello @thomasvdb 

You are right, included documents are missing from the .NET library.

I'm going to add them and release a new version of the library during this month.

I'll let you know in this issue when it will be available.

**Comment by stephdewit** [comment]
Hello @thomasvdb 

It took a little bit longer than expected, but starting with the current 0.5.16 release, each document now contains the reference of the client owning it.
