### ISSUE TITLE
businessRegisterScan

### ISSUE THREAD

**Issue by mvanhil** [ibanity/ibanity-dotnet#6]
Hi, 

I noticed that for creating a new supplier a field is missing: businessRegisterScan
https://documentation.ibanity.com/einvoicing/1/api/curl#create-supplier 

Is this field required for registering a new supplier and if yes, can this field be added please? 

Thanks
Marnik

**Comment by damienbr** [comment]
Hey Marnik, 
Thanks for reaching out.
I'll add the missing field.

**Comment by damienbr** [comment]
Fixed in https://github.com/ibanity/ibanity-dotnet/releases/tag/0.5.7
